version: '3.8'
services:
  erlang_app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=todo_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
